baseURL = 'https://matthewpenney.net'
locale = 'en-gb'
title = "Matthew Penney"

theme = 'hello-friend-ng'

[markup]
    
    [markup.goldmark]

        [markup.goldmark.renderer]

            unsafe = true

[params.logo]

    logoText = "matthewpenney.net"
    logoHomeLink = "/"

[params]

    enableThemeToggle = true
    homeSubtitle = "Systems Programmer based in London, UK"

    [[params.social]]

        name = "github"
        url = "https://github.com/mj-penney"

    [[params.social]]

        name = "linkedin"
        url = "https://www.linkedin.com/in/matthew-penney-9979851a4"

    [[params.social]]

        name = "email"
        url = "mailto:matt@matthewpenney.net"

[menu]

    [[menu.main]]

        identifier = "posts"
        name = "Posts"
        url = "/posts/"

#    [[menu.main]]
#
#        identifier = "projects"
#        name = "Projects"
#        url = "/projects/"
